### ISSUE TITLE
Chunk Type 0x1F

### ISSUE THREAD

**Issue by tlong-dev** [RobloxAPI/rbxfile#11]
Love this work, fantastic job. This project doesn't seem active, but it's been useful to me.

There appears to be an unaccounted for Property Type within some files `0x1F`. 

Comparing values.go across `master` and `v0.4.3` it seems like `master` supports even fewer types and I don't know of any other sources where this information could be.

Any advice on just adding an "UnknownProperty" fallback?

**Comment by Anaminus** [comment]
Most work is being done on the [refactor](https://github.com/RobloxAPI/rbxfile/tree/refactor) branch. The API is different, but it's much more up to date. It also has better support for chunk errors and handling of unknown chunks. I should probably just merge it already.

Anyway, 0x1F corresponds to a recently added "UniqueId" type, which is used by the UniqueId property that is present on each instance. Each value is a 16-byte sequence that is probably unique per file. It's a lot easier to see in the RBXLX format.

I haven't implemented it yet because there's evidence that the encoding of UniqueId for the binary format is more complicated than it first appears. It's also difficult to work with because the values are regenerated on every encoding, so it's impossible to match a value in the RBXL format to its RBXLX equivalent. I'm planning on doing a few more checks before deciding on the correct implementation.

**Comment by tlong-dev** [comment]
Thanks for the response, I appreciate it.

UniqueId sounds uniquely useless, I'll continue to ignore it as a warning for now then and check out the refactor branch!

**Comment by Anaminus** [comment]
I'm going to keep this open to track the progress of the UniqueId type.

**Comment by Anaminus** [comment]
UniqueId has been implemented by aab804edee29fe9bee73bdc28712039dbcc1794b.
